# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cherniak\Desktop\QTDSoZSync\venv\Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.FFTHolder = QtWidgets.QVBoxLayout()
        self.FFTHolder.setObjectName("FFTHolder")
        self.gridLayout.addLayout(self.FFTHolder, 0, 1, 1, 1)
        self.GraphHolder = QtWidgets.QVBoxLayout()
        self.GraphHolder.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.GraphHolder.setObjectName("GraphHolder")
        self.gridLayout.addLayout(self.GraphHolder, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.SearchDelayB = QtWidgets.QPushButton(self.centralwidget)
        self.SearchDelayB.setMinimumSize(QtCore.QSize(100, 0))
        self.SearchDelayB.setMaximumSize(QtCore.QSize(89, 16777215))
        self.SearchDelayB.setObjectName("SearchDelayB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SearchDelayB)
        self.ThorSN = QtWidgets.QLineEdit(self.centralwidget)
        self.ThorSN.setMinimumSize(QtCore.QSize(100, 0))
        self.ThorSN.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ThorSN.setObjectName("ThorSN")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ThorSN)
        self.DelayT = QtWidgets.QLineEdit(self.centralwidget)
        self.DelayT.setMinimumSize(QtCore.QSize(100, 0))
        self.DelayT.setMaximumSize(QtCore.QSize(100, 16777215))
        self.DelayT.setObjectName("DelayT")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DelayT)
        self.ConnectCoraB = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectCoraB.setMinimumSize(QtCore.QSize(100, 0))
        self.ConnectCoraB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ConnectCoraB.setObjectName("ConnectCoraB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ConnectCoraB)
        self.IPT = QtWidgets.QLineEdit(self.centralwidget)
        self.IPT.setMinimumSize(QtCore.QSize(100, 0))
        self.IPT.setMaximumSize(QtCore.QSize(100, 16777215))
        self.IPT.setObjectName("IPT")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.IPT)
        self.PORTT = QtWidgets.QLineEdit(self.centralwidget)
        self.PORTT.setMinimumSize(QtCore.QSize(100, 0))
        self.PORTT.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PORTT.setObjectName("PORTT")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.PORTT)
        self.RunMeas = QtWidgets.QPushButton(self.centralwidget)
        self.RunMeas.setMinimumSize(QtCore.QSize(100, 0))
        self.RunMeas.setMaximumSize(QtCore.QSize(100, 16777215))
        self.RunMeas.setObjectName("RunMeas")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.RunMeas)
        self.NRunsT = QtWidgets.QLineEdit(self.centralwidget)
        self.NRunsT.setMinimumSize(QtCore.QSize(100, 0))
        self.NRunsT.setMaximumSize(QtCore.QSize(100, 16777215))
        self.NRunsT.setObjectName("NRunsT")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.NRunsT)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(100, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.progressBar)
        self.StoreMeas = QtWidgets.QCheckBox(self.centralwidget)
        self.StoreMeas.setChecked(True)
        self.StoreMeas.setObjectName("StoreMeas")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.StoreMeas)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LogBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LogBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LogBox.setObjectName("LogBox")
        self.verticalLayout.addWidget(self.LogBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMotorCntrl = QtWidgets.QMenu(self.menubar)
        self.menuMotorCntrl.setObjectName("menuMotorCntrl")
        self.menuPostCalc = QtWidgets.QMenu(self.menubar)
        self.menuPostCalc.setObjectName("menuPostCalc")
        self.menuFFT = QtWidgets.QMenu(self.menuPostCalc)
        self.menuFFT.setObjectName("menuFFT")
        self.menuZero_Fit = QtWidgets.QMenu(self.menuPostCalc)
        self.menuZero_Fit.setObjectName("menuZero_Fit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionThorlabs = QtWidgets.QAction(MainWindow)
        self.actionThorlabs.setObjectName("actionThorlabs")
        self.actionOz_ODL = QtWidgets.QAction(MainWindow)
        self.actionOz_ODL.setObjectName("actionOz_ODL")
        self.actionLoad_Graph = QtWidgets.QAction(MainWindow)
        self.actionLoad_Graph.setObjectName("actionLoad_Graph")
        self.actionBlackman = QtWidgets.QAction(MainWindow)
        self.actionBlackman.setObjectName("actionBlackman")
        self.actionHanning = QtWidgets.QAction(MainWindow)
        self.actionHanning.setObjectName("actionHanning")
        self.actionHann = QtWidgets.QAction(MainWindow)
        self.actionHann.setObjectName("actionHann")
        self.actionZero_Fit = QtWidgets.QAction(MainWindow)
        self.actionZero_Fit.setObjectName("actionZero_Fit")
        self.actionNone = QtWidgets.QAction(MainWindow)
        self.actionNone.setObjectName("actionNone")
        self.actionFull = QtWidgets.QAction(MainWindow)
        self.actionFull.setObjectName("actionFull")
        self.actionSmall = QtWidgets.QAction(MainWindow)
        self.actionSmall.setObjectName("actionSmall")
        self.actionFind_Peaks = QtWidgets.QAction(MainWindow)
        self.actionFind_Peaks.setObjectName("actionFind_Peaks")
        self.actionCalc_refrectiv = QtWidgets.QAction(MainWindow)
        self.actionCalc_refrectiv.setObjectName("actionCalc_refrectiv")
        self.actionCalc_thikness = QtWidgets.QAction(MainWindow)
        self.actionCalc_thikness.setObjectName("actionCalc_thikness")
        self.actionCalc_Absorbtion = QtWidgets.QAction(MainWindow)
        self.actionCalc_Absorbtion.setObjectName("actionCalc_Absorbtion")
        self.menuMenu.addAction(self.actionExit)
        self.menuMotorCntrl.addAction(self.actionThorlabs)
        self.menuMotorCntrl.addAction(self.actionOz_ODL)
        self.menuFFT.addAction(self.actionBlackman)
        self.menuFFT.addAction(self.actionHanning)
        self.menuFFT.addAction(self.actionHann)
        self.menuFFT.addSeparator()
        self.menuFFT.addAction(self.actionNone)
        self.menuZero_Fit.addAction(self.actionFull)
        self.menuZero_Fit.addAction(self.actionSmall)
        self.menuPostCalc.addAction(self.actionLoad_Graph)
        self.menuPostCalc.addAction(self.menuMake_AVG.menuAction())
        self.menuPostCalc.addAction(self.menuFFT.menuAction())
        self.menuPostCalc.addAction(self.menuZero_Fit.menuAction())
        self.menuPostCalc.addSeparator()
        self.menuPostCalc.addAction(self.actionFind_Peaks)
        self.menuPostCalc.addAction(self.actionCalc_refrectiv)
        self.menuPostCalc.addAction(self.actionCalc_thikness)
        self.menuPostCalc.addAction(self.actionCalc_Absorbtion)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMotorCntrl.menuAction())
        self.menubar.addAction(self.menuPostCalc.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchDelayB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scans for connected delay line.<br/>Should be Thorlabs KBD101<br/>or OZ-Optics ODL</p><p>Only one delay line should be connected at the same time.</p></body></html>"))
        self.SearchDelayB.setText(_translate("MainWindow", "Search delay line"))
        self.ThorSN.setToolTip(_translate("MainWindow", "<html><head/><body><p>Thorlabs S/N</p></body></html>"))
        self.ThorSN.setText(_translate("MainWindow", "28250359"))
        self.DelayT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Found device</p></body></html>"))
        self.DelayT.setText(_translate("MainWindow", "None..."))
        self.ConnectCoraB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Connects to FPGA with ARM board.<br/>IP may varie</p></body></html>"))
        self.ConnectCoraB.setText(_translate("MainWindow", "Connect to Cora"))
        self.IPT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ip. Addr. of FPGA-Board</p></body></html>"))
        self.IPT.setText(_translate("MainWindow", "134.91.61.197"))
        self.PORTT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Portnumber</p></body></html>"))
        self.PORTT.setText(_translate("MainWindow", "7"))
        self.RunMeas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Runs the measurement routine for n times of the right value.</p></body></html>"))
        self.RunMeas.setText(_translate("MainWindow", "Run meas"))
        self.NRunsT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of runs</p></body></html>"))
        self.NRunsT.setText(_translate("MainWindow", "1"))
        self.StoreMeas.setText(_translate("MainWindow", "Store Measurement"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuMotorCntrl.setTitle(_translate("MainWindow", "MotorCntrl"))
        self.menuPostCalc.setTitle(_translate("MainWindow", "PostCalc"))
        self.menuFFT.setTitle(_translate("MainWindow", "FFT"))
        self.menuZero_Fit.setTitle(_translate("MainWindow", "Zero Fit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionThorlabs.setText(_translate("MainWindow", "Thorlabs"))
        self.actionOz_ODL.setText(_translate("MainWindow", "Oz ODL"))
        self.actionLoad_Graph.setText(_translate("MainWindow", "Load Graph"))
        self.actionBlackman.setText(_translate("MainWindow", "Blackman"))
        self.actionHanning.setText(_translate("MainWindow", "Hanning"))
        self.actionHann.setText(_translate("MainWindow", "Hann"))
        self.actionZero_Fit.setText(_translate("MainWindow", "Zero Fit"))
        self.actionNone.setText(_translate("MainWindow", "None"))
        self.actionFull.setText(_translate("MainWindow", "Full"))
        self.actionSmall.setText(_translate("MainWindow", "Small"))
        self.actionFind_Peaks.setText(_translate("MainWindow", "Find Peaks"))
        self.actionCalc_refrectiv.setText(_translate("MainWindow", "Calc refrectiv"))
        self.actionCalc_thikness.setText(_translate("MainWindow", "Calc thikness"))
        self.actionCalc_Absorbtion.setText(_translate("MainWindow", "Calc Absorbtion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
