# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Vlady\Desktop\PythonCodeQTDS\Thorlabs.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(296, 347)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 21, 278, 281))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.VelT = QtWidgets.QLineEdit(self.widget)
        self.VelT.setObjectName("VelT")
        self.verticalLayout.addWidget(self.VelT)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.AccelT = QtWidgets.QLineEdit(self.widget)
        self.AccelT.setObjectName("AccelT")
        self.verticalLayout.addWidget(self.AccelT)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.HVelT = QtWidgets.QLineEdit(self.widget)
        self.HVelT.setObjectName("HVelT")
        self.verticalLayout.addWidget(self.HVelT)
        self.ApplyB = QtWidgets.QPushButton(self.widget)
        self.ApplyB.setObjectName("ApplyB")
        self.verticalLayout.addWidget(self.ApplyB)
        self.HomeB = QtWidgets.QPushButton(self.widget)
        self.HomeB.setObjectName("HomeB")
        self.verticalLayout.addWidget(self.HomeB)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.StartPos = QtWidgets.QLineEdit(self.widget)
        self.StartPos.setObjectName("StartPos")
        self.verticalLayout_3.addWidget(self.StartPos)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.StartMeasPos = QtWidgets.QLineEdit(self.widget)
        self.StartMeasPos.setObjectName("StartMeasPos")
        self.verticalLayout_3.addWidget(self.StartMeasPos)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.StopMeasPos = QtWidgets.QLineEdit(self.widget)
        self.StopMeasPos.setObjectName("StopMeasPos")
        self.verticalLayout_3.addWidget(self.StopMeasPos)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.EndPos = QtWidgets.QLineEdit(self.widget)
        self.EndPos.setObjectName("EndPos")
        self.verticalLayout_3.addWidget(self.EndPos)
        self.SetParam = QtWidgets.QPushButton(self.widget)
        self.SetParam.setObjectName("SetParam")
        self.verticalLayout_3.addWidget(self.SetParam)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.PositionSlide = QtWidgets.QSlider(self.widget)
        self.PositionSlide.setMinimum(1)
        self.PositionSlide.setProperty("value", 1)
        self.PositionSlide.setSliderPosition(1)
        self.PositionSlide.setOrientation(QtCore.Qt.Vertical)
        self.PositionSlide.setInvertedAppearance(True)
        self.PositionSlide.setObjectName("PositionSlide")
        self.gridLayout.addWidget(self.PositionSlide, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 296, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Velocity in mm/s"))
        self.VelT.setText(_translate("MainWindow", "160"))
        self.label_2.setText(_translate("MainWindow", "Acceleration in mm/s^2"))
        self.AccelT.setText(_translate("MainWindow", "2000"))
        self.label_3.setText(_translate("MainWindow", "Velocity in mm/s"))
        self.HVelT.setText(_translate("MainWindow", "120"))
        self.ApplyB.setText(_translate("MainWindow", "Apply"))
        self.HomeB.setText(_translate("MainWindow", "Home"))
        self.label_4.setText(_translate("MainWindow", "Start Position"))
        self.StartPos.setText(_translate("MainWindow", "40"))
        self.label_5.setText(_translate("MainWindow", "Start Measurement"))
        self.StartMeasPos.setText(_translate("MainWindow", "50"))
        self.label_6.setText(_translate("MainWindow", "End Measurement"))
        self.StopMeasPos.setText(_translate("MainWindow", "60"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.EndPos.setText(_translate("MainWindow", "80"))
        self.SetParam.setText(_translate("MainWindow", "Apply"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
